### ISSUE TITLE
Keyboard shortcut chord has changed

### ISSUE THREAD

**Issue by uejji** [ShadowBlip/InputPlumber#193]
It seems that Steam has changed the shortcut chord to bring up the on screen keyboard with an xbox controller to Guide+Select/Back/View.  However, InputPlumber is still sending the old chord Guide+X.

**Comment by philmmanjaro** [comment]
Well, there are two profiles now. Xbox and Xbox Elite. We will check.

**Comment by pastaq** [comment]
This is a bug in the steam client introduced when they tried to unify the big picture and steam deck mode chords. It wasn't an intentional change. This only affects Xbox controllers. Submit a bug report to Valve so they can change it back. We can't really support two separate chords for the same capability.

**Comment by uejji** [comment]
Okay.  Since it's not an InputPlumber bug, I'm closing the issue.
